name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - 2.13.3
          - 2.12.12

    steps:
    - uses: actions/checkout@v2

    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    - name: Setup Java
      uses: olafurpg/setup-scala@v5
      with:
        java-version: openjdk@1.11

    - name: Run tests ${{ matrix.scala }}
      run: sbt ++${{ matrix.scala }} clean coverage test

    - name: Report test coverage
      if: success()
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: sbt ++${{ matrix.scala }} coverageReport coverageAggregate coveralls

    - name: Slack notification
      uses: homoluctus/slatify@master
      if: failure() && github.ref == 'refs/heads/master'
      with:
        type: ${{ job.status }}
        job_name: Build
        url: ${{ secrets.SLACK_WEBHOOK }}
